### ISSUE TITLE
Received Mail to reset password Not Working

### ISSUE THREAD

**Issue by chamanbharti** [rahiakela/technocracy-v1.3.0.0#2]
![image](https://user-images.githubusercontent.com/24896958/47720865-e3257500-dc74-11e8-84a9-fbe1900c08ef.png)
**When presss the recieved link it shows 500 Internal Server Error**
![image](https://user-images.githubusercontent.com/24896958/47720968-1b2cb800-dc75-11e8-87fe-a34023235ce3.png)

**Comment by rahiakela** [comment]
Actually, this is not issue because you are testing dev environment but mail link is referring to prod environment. so I am closing it.
